### ISSUE TITLE
License clarification

### ISSUE THREAD

**Issue by Br3nda** [Mictronics/GaugeMeter#6]
inside GaugeMeter.js there is this comment
"Copyright AshAlom.com  All rights reserved."

there is also a LICENCE file saying MIT licence

which is true?
Is it open source, or is it all rights reserved?

**Comment by Mictronics** [comment]
The copyright has been left in there because it's part of the original code. The author, AshAlom, has abandoned the code and I'm going to maintain and extend it when needed.
My code base is released under MIT and therefore open source.

**Comment by Br3nda** [comment]
Okay. So you're saying the original code is All Rights Reserved and we have no right to use or modify it.

**Comment by Mictronics** [comment]
"All Rights Reserved" is the initial authors statement in its code. Which in turn was not including a license file. I see no real problem here. The original copyright statement is still included in code together with a clear statement that any future version is modified for bug fixing and extension.

I don't see your reason for using the unmodified, original code base. Includes several bugs and has limited functionality already compared to newer versions.
